version: '0.1'

services:
  vllm-service:
    image: vllm/vllm-openai:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    environment:
      - HUGGING_FACE_HUB_TOKEN=${HUGGING_FACE_HUB_TOKEN}
    ports:
      - 8000:8000
    ipc: host
    command: --model unsloth/tinyllama-chat-bnb-4bit --quantization bitsandbytes --load-format bitsandbytes

  streamlit-app:
    build:
      context: .
      dockerfile: ./frontend/build/Dockerfile
    ports:
      - 8501:8501
    environment:
      - VLLM_API_URL=${VLLM_API_URL}
    depends_on:
      - vllm-service